### ISSUE TITLE
The link to the YT vid to get the oauth code is now privated

### ISSUE THREAD

**Issue by Netw0rkingN3rd** [EionRobb/purple-hangouts-attempt2#237]
https://www.youtube.com/watch?v=hlDhp-eNLMU - is privated. Perhaps change line 395 in libhangouts.c to a new video link on vimeo or whatever?

**Comment by arifsaha** [comment]
I think we need to have step by step instruction text in the dialog box as well. Of course video can be better by many people but for others especially that just need reminder, some text instructions can be enough. Alternatively, instructions - in text and even video - can be part of the Github repo under documentation directory.

**Comment by EionRobb** [comment]
Yeah, I've asked @dequis if she can un-private it, but probably needs a new one done since most people don't have annotations on any more, so weren't seeing the text

I don't think I can beat the speedrun score either ;(

I'm also making another attempt at a Pidgin-only plugin that will do the auth in an embedded webbrowser as part of the new https://github.com/EionRobb/purple-googlechat plugin

**Comment by dequis** [comment]
>Yeah, I've asked @dequis if she can un-private it

Oops totally missed that you asked. I put it back to unlisted.
