### ISSUE TITLE
runtime dependencies?

### ISSUE THREAD

**Issue by unhammer** [EionRobb/purple-hangouts-attempt2#240]
What are the runtime dependencies on Debian? (What can one delete after compiling and installing?)

(pretty sure I don't need `protobuf-c-compiler make git`, and the `-dev` packages but guessing some of the others are needed)

**Comment by EionRobb** [comment]
Ah, you might want to look at the Google Chat plugin instead of the Hangouts plugin (I believe that Hangouts might be turning off soon?), but yes, same runtime deps there.

The runtime deps should just be  libpurple, libprotobuf-c, libjson-glib-1.0, libglib-2.0 and zlib

If you're looking for someone else to do the builds for you, you might be able to use the webupd8 PPA, though I haven't checked in any time recently to see how up to date that is with the latest plugins.

Hope that helps :)
